### ISSUE TITLE
Unable to find the pip package

### ISSUE THREAD

**Issue by painor** [SuperVegetoo/directory_downloader#2]
while following the instructions in the readme I couldn't get past the installation part.
![image](https://user-images.githubusercontent.com/30215770/92330830-f2905900-f069-11ea-8e6b-eb094a62bc61.png)
` ERROR: Could not find a version that satisfies the requirement directory_downloader (from versions: none)`
`ERROR: No matching distribution found for directory_downloader`

**Comment by mahdinaija7** [comment]
not published yet

**Comment by mahdinaija7** [comment]
Fixed !!!
